### ISSUE TITLE
Should we swap to an ATDIS feed

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/lismore#1]
https://github.com/openaustralia/planningalerts/issues/920

We have:
http://tracker.lismore.nsw.gov.au/atdis/1.0/applications.json

**Comment by LoveMyData** [comment]
why not if it is a json feed, much easier, can you explain more when we are at the heckfest?

**Comment by CloCkWeRX** [comment]
Short story:
There's a gem (https://github.com/planningalerts-scrapers/atdisplanningalertsfeed) that handles a type of feed that handles things as per https://www.planningalerts.org.au/atdis/specification

_Some_ scrapers are much more efficient/better/more accurate; others... the web UI is still the way to go.

Example scraper:
https://github.com/planningalerts-scrapers/maitland/blob/master/scraper.rb

**Comment by LoveMyData** [comment]
@CloCkWeRX , I did a check and quick answer is no switching to the feed.

Web site is showing 33 applications for this Month
http://tracker.lismore.nsw.gov.au/Application/AdvancedSearchResult?DateFrom=1%2f05%2f2016&DateTo=13%2f05%2f2016&DateType=1&RemoveUndeterminedApplications=False&ApplicationType=5%2c8%2c10%2c13&ShowOutstandingApplications=False&ShowExhibitedApplications=False&IncludeDocuments=False

Feed search only have 3 applications for the last 30 days
http://tracker.lismore.nsw.gov.au/atdis/1.0/applications.json?lodgement_date_start=2016-04-13

**Comment by CloCkWeRX** [comment]
I agree... sigh, Civica

**Comment by CloCkWeRX** [comment]
I haven't had much luck with writing to councils like Upper Hunter Shire who also use Civica, if you feel super keen might be worth at least asking them to investigate; otherwise...
